
  @hostname=127.0.0.1
  @port=3000
  @host={{hostname}}:{{port}}
  
  ###
  POST http://{{host}}/stock/searchStock.json HTTP/1.1
  content-type: application/json;charset=UTF-8
  
  {
    "content":"zxzq"
  }
